version: 2.1
jobs:
  test:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Set up tox tests
          command: pip install --upgrade tox
      - restore_cache:
          keys:
            - v1-poetry-deps-{{ checksum "poetry.lock" }}
            - v1-poetry-deps-
      - run:
          name: Set up neo4j and run tests
          command: .circleci/run_neo_tests.sh
      - save_cache:
          key: v1-poetry-deps-{{ checksum "poetry.lock" }}
          paths:
            - .tox
  publish-pypi:
    docker:
      - image: cimg/python:3.9
    steps:
      - add_ssh_keys:
          fingerprints:
            - "bc:ea:b2:4f:1c:a4:7d:6e:d8:6b:ad:57:15:0e:52:d4"
      - checkout
      - run:
          name: Publish package to pypi
          command: poetry publish --build --username __token__ --password $PYPI_API_TOKEN
      - run:
          name: Create git tag
          command: pip install -U toml && git tag v$(python3 .circleci/parse_version.py)
      - run:
          name: Push git tag
          command: git push --tags
workflows:
  version: 2
  build_test_deploy:
    jobs:
      - test:
          context: polaris-foundation
      - publish-pypi:
          context: polaris-foundation
          requires:
            - test
          filters:
            branches:
              only:
                - main
